package harness

import (
	"fmt"
	"runtime"
	"strings"
)

const (
	ProbeLaunch       = "launch"
	ProbeTrustPrompt  = "trust-prompt"
	ProbeHook         = "hook-fires"
	ProbeComposer     = "composer-detect"
	ProbeSubmit       = "submit"
	ProbeTurnBoundary = "turn-boundary"
)

type ProbeResult struct {
	Name   string
	Passed bool
	Detail string
}

type CheckReport struct {
	Collar         string
	HarnessVersion string
	Results        []ProbeResult
}

func RequiredProbes() []string {
	return []string{
		ProbeLaunch,
		ProbeTrustPrompt,
		ProbeHook,
		ProbeComposer,
		ProbeSubmit,
		ProbeTurnBoundary,
	}
}

func (report CheckReport) Passed() bool {
	if len(report.Results) != len(RequiredProbes()) {
		return false
	}
	seen := make(map[string]bool, len(report.Results))
	for _, result := range report.Results {
		if !result.Passed || seen[result.Name] {
			return false
		}
		seen[result.Name] = true
	}
	for _, name := range RequiredProbes() {
		if !seen[name] {
			return false
		}
	}
	return true
}

func (report CheckReport) IssueBody() string {
	var body strings.Builder
	fmt.Fprintf(&body, "## Collar compatibility failure\n\n")
	fmt.Fprintf(&body, "- Collar: `%s`\n", report.Collar)
	fmt.Fprintf(&body, "- Harness version: `%s`\n", report.HarnessVersion)
	fmt.Fprintf(&body, "- Platform: `%s/%s`\n\n", runtime.GOOS, runtime.GOARCH)
	body.WriteString("## Probes\n\n")
	for _, result := range report.Results {
		mark := " "
		if result.Passed {
			mark = "x"
		}
		fmt.Fprintf(&body, "- [%s] `%s`", mark, result.Name)
		if result.Detail != "" {
			fmt.Fprintf(&body, " — %s", result.Detail)
		}
		body.WriteByte('\n')
	}
	body.WriteString("\nGenerated by `gang collar check`; review terminal evidence before submitting.\n")
	return body.String()
}

func (report CheckReport) IssueCommand(repository string) string {
	title := fmt.Sprintf("%s collar is incompatible with %s", report.Collar, report.HarnessVersion)
	return "gh issue create --repo " + shellJoin([]string{repository}) +
		" --title " + shellJoin([]string{title}) +
		" --body " + shellJoin([]string{report.IssueBody()})
}
