#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Turn a short, local film clip into the Gangline hero's ASCII frame array.

The source film is deliberately an input, not a site asset. See
evidence/FOOTAGE.md for the recorded source, licence, and exact invocation.
Requires ffmpeg (set FFMPEG=/path/to/ffmpeg when it is not on PATH).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path


RAMP = "█▓▒░ "  # Dark source pixels become the densest printed blocks.


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="downloaded source video")
    parser.add_argument("--output", type=Path, default=Path("site/mushing-frames.js"))
    parser.add_argument("--start", type=float, default=20.0, help="clip start in seconds")
    parser.add_argument("--duration", type=float, default=4.0, help="clip duration in seconds")
    parser.add_argument("--fps", type=int, default=8)
    parser.add_argument("--columns", type=int, default=88)
    parser.add_argument("--rows", type=int, default=27)
    parser.add_argument("--fade-frames", type=int, default=6)
    parser.add_argument("--crop", default="1440:810:240:90", help="ffmpeg crop expression before scaling")
    return parser.parse_args()


def source_frames(args: argparse.Namespace) -> list[bytes]:
    ffmpeg = os.environ.get("FFMPEG", "ffmpeg")
    if not shutil.which(ffmpeg):
        raise SystemExit(f"ffmpeg was not found: {ffmpeg}")
    command = [
        ffmpeg, "-hide_banner", "-loglevel", "error", "-ss", str(args.start),
        "-i", str(args.input), "-t", str(args.duration), "-vf",
        f"crop={args.crop},fps={args.fps},scale={args.columns}:{args.rows}:flags=lanczos,format=gray",
        "-f", "rawvideo", "-",
    ]
    raw = subprocess.run(command, check=True, stdout=subprocess.PIPE).stdout
    size = args.columns * args.rows
    if len(raw) % size:
        raise SystemExit("ffmpeg returned a partial grayscale frame")
    frames = [raw[offset : offset + size] for offset in range(0, len(raw), size)]
    if len(frames) < args.fade_frames * 2:
        raise SystemExit("clip is too short for the requested closing crossfade")
    return frames


def fade_loop(frames: list[bytes], count: int) -> list[bytes]:
    """Crossfade the closing frames to the opening pose for an unobtrusive loop."""
    result = frames[:]
    for offset in range(count):
        weight = (offset + 1) / count
        source = frames[-count + offset]
        opening = frames[offset]
        result[-count + offset] = bytes(
            round((1 - weight) * old + weight * new)
            for old, new in zip(source, opening, strict=True)
        )
    # The closing blend ends on opening frame count - 1. Removing the same
    # opening frames makes the following wrap land on its natural successor.
    return result[count:]


def ascii_frame(frame: bytes, columns: int) -> str:
    chars = [RAMP[pixel * (len(RAMP) - 1) // 255] for pixel in frame]
    return "\n".join("".join(chars[offset : offset + columns]) for offset in range(0, len(chars), columns))


def main() -> None:
    args = parse_args()
    frames = fade_loop(source_frames(args), args.fade_frames)
    rendered = [ascii_frame(frame, args.columns) for frame in frames]
    payload = json.dumps(rendered, ensure_ascii=False, separators=(",", ":"))
    js = f'''/* Generated by site/tools/render_mushing_ascii.py; do not hand-edit. */
const mushingFrames={payload};
const mushing=document.querySelector("#mushing");
const reduced=matchMedia("(prefers-reduced-motion: reduce)");
let frame=0;
function renderMushing() {{
  mushing.textContent=mushingFrames[frame];
}}
function animateMushing() {{
  if (reduced.matches) return;
  frame=(frame+1)%mushingFrames.length;
  renderMushing();
  setTimeout(animateMushing,{1000 // args.fps});
}}
renderMushing();
animateMushing();
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(js, encoding="utf-8")
    print(f"wrote {args.output} ({args.output.stat().st_size} bytes; {len(rendered)} frames)")


if __name__ == "__main__":
    main()
